# Generated by Django 4.2.11 on 2024-04-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('account_no', models.PositiveIntegerField(auto_created=True, default=1, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
